import Vue from 'vue';
import MaterialIcons from '@dbetka/vue-material-icons'; // sets just the max size
import es from 'vuetify/es5/locale/es';
import Vuetify, {
  VApp,
  VCard,
  VNavigationDrawer,
  VDivider,
  VMain,
  VFooter,
  VDialog,
  VListItem,
  VBtn,
  VIcon,
  VListItemContent,
  VListItemTitle,
  VListItemAvatar,
  VListItemSubtitle,
  VListItemIcon,
  VListGroup,
  VMenu,
  VSwitch,
  VBtnToggle,
  VAvatar,
  VAutocomplete,
  VSnackbar,
  VProgressLinear,
  VRow,
  VCol,
  VTooltip,
  VSkeletonLoader,
  VDataTable,
  VSelect,
  VSimpleTable,
  VContainer,
  VTextField,
  VCardTitle,
  VCardSubtitle,
  VForm,
  VTextarea,
  VCardActions,
  VCardText,
  VSpacer,
  VProgressCircular,
  VAppBar,
  VToolbarTitle,
  VAppBarNavIcon,
  VImg,
  VList,
  VListItemGroup,
  VCheckbox,
  VChip,
  VDatePicker,
  VBadge,
  VAlert,
  VTabs,
  VTab,
  VTabItem,
  VFileInput,
  VStepper,
  VStepperHeader,
  VStepperStep,
  VStepperItems,
  VStepperContent,
  VBreadcrumbs,
  VBreadcrumbsItem,
  VRadioGroup,
  VRadio,
  VSlider,
  VRangeSlider,
  VCalendar,
  VSheet,
  VExpansionPanel,
  VExpansionPanels,
  VExpansionPanelHeader,
  VExpansionPanelContent,
  VToolbar,
  VTimeline,
  VTimelineItem,
} from 'vuetify/lib';

Vue.use(Vuetify, {
  components: {
    VApp,
    VCard,
    VNavigationDrawer,
    VDivider,
    VMain,
    VFooter,
    VDialog,
    VListItem,
    VBtn,
    VIcon,
    VListItemContent,
    VListItemTitle,
    VListItemAvatar,
    VListItemSubtitle,
    VListItemIcon,
    VListGroup,
    VMenu,
    VSwitch,
    VBtnToggle,
    VAvatar,
    VAutocomplete,
    VSnackbar,
    VProgressLinear,
    VRow,
    VCol,
    VTooltip,
    VSkeletonLoader,
    VDataTable,
    VSelect,
    VSimpleTable,
    VContainer,
    VTextField,
    VCardTitle,
    VCardSubtitle,
    VForm,
    VTextarea,
    VCardActions,
    VCardText,
    VSpacer,
    VProgressCircular,
    VAppBar,
    VToolbarTitle,
    VAppBarNavIcon,
    VImg,
    VList,
    VListItemGroup,
    VCheckbox,
    VChip,
    VDatePicker,
    VBadge,
    VAlert,
    VTabs,
    VTab,
    VTabItem,
    VFileInput,
    VStepper,
    VStepperHeader,
    VStepperStep,
    VStepperItems,
    VStepperContent,
    VBreadcrumbs,
    VBreadcrumbsItem,
    VRadioGroup,
    VRadio,
    VSlider,
    VRangeSlider,
    VCalendar,
    VSheet,
    VExpansionPanel,
    VExpansionPanels,
    VExpansionPanelHeader,
    VExpansionPanelContent,
    VToolbar,
    VTimeline,
    VTimelineItem,
  }
});
Vue.use(MaterialIcons);

const opts = {
  options: {
    customProperties: true
  },
  icons: {
    iconfont: 'mdiSvg'
  },
  theme: {
    options: {
      customProperties: true
    },
    themes: {
      light: {
        primary: '#255EA6',
        secondary: '#555F71',
        accent: '#82B1FF',
        info: '#1680c2',
        warning: '#f9c100',
        error: '#d31419',
        success: '#449935',
        backgroundColor: '#FFF',
        fontColor: '#303030',
        linkActive: '#E5EAF2',
        ciudadaniaBase: '#1C2C84',
        brightnessText: '#FFF'
      },
      dark: {
        primary: '#A7C8FF',
        secondary: '#BDC7DC',
        accent: '#82B1FF',
        info: '#88dbf7',
        warning: '#f9c100',
        error: '#d31419',
        success: '#449935',
        backgroundColor: '#303030',
        fontColor: '#FFF',
        linkActive: '#5b5b5b',
        ciudadaniaBase: '#85CEFF',
        brightnessText: '#0A0A0A'
      }
    }
  },
  lang: {
    locales: { es },
    current: 'es'
  }
};

export default new Vuetify(opts);
